# Generated by Django 4.0 on 2022-05-04 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_type', models.SmallAutoField(db_column='incident_type', primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('reporting_medium', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sasai', 'Sasai'), ('phone call', 'Phone Call'), ('sms', 'SMS'), ('social media or email', 'Social Media or Email')], default='whatsapp', max_length=21)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ball_dropper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'incident_type',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
